import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'

export default function Home() {
  return (
    <div className={styles.container} >
      <Head>
        <title>World of Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
        Wellcome to the World of Blog
        </h1>

        <Image src="/b1.avif" alt="" height='137' width='258' />
        <div className={styles.blog}>
        <p className={styles.description}>
        Latest Blog
        </p>
         
          <div className={styles.blogItem}>
          <h3>learn JavaScript</h3> 
            <h6>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Sed maiores, minima velit recusandae consequatur doloribus ex, ea quidem, pariatur repellendus maxime eaque fuga deleniti asperiores corporis dolor? Soluta eligendi cum architecto porro voluptas vitae.</h6>
          </div><hr/> 
          <div className={styles.blogItem}>
          <h3>learn ReactJs</h3>  
            <h6>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Sed maiores, minima velit recusandae consequatur doloribus ex, ea quidem, pariatur repellendus maxime eaque fuga deleniti asperiores corporis dolor? Soluta eligendi cum architecto porro voluptas vitae.</h6>
            </div><hr/> 
            <div className={styles.blogItem}>
          <h3> learn NodeJs</h3> 
            <h6>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Sed maiores, minima velit recusandae consequatur doloribus ex, ea quidem, pariatur repellendus maxime eaque fuga deleniti asperiores corporis dolor? Soluta eligendi cum architecto porro voluptas vitae.</h6>
            </div>
        </div>

       
      </main>

      <footer className={styles.footer}>
       
      </footer>
    </div>
  )
}
